# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.comboBoxRoastLevel = QtWidgets.QComboBox(parent=Dialog)
        self.comboBoxRoastLevel.setObjectName("comboBoxRoastLevel")
        self.comboBoxRoastLevel.addItem("")
        self.comboBoxRoastLevel.addItem("")
        self.comboBoxRoastLevel.addItem("")
        self.verticalLayout.addWidget(self.comboBoxRoastLevel)
        self.comboBoxType = QtWidgets.QComboBox(parent=Dialog)
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.verticalLayout.addWidget(self.comboBoxType)
        self.lineEditTasteDescription = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditTasteDescription.setObjectName("lineEditTasteDescription")
        self.verticalLayout.addWidget(self.lineEditTasteDescription)
        self.doubleSpinBoxPrice = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.doubleSpinBoxPrice.setMinimum(0.0)
        self.doubleSpinBoxPrice.setMaximum(999.99)
        self.doubleSpinBoxPrice.setProperty("value", 0.0)
        self.doubleSpinBoxPrice.setObjectName("doubleSpinBoxPrice")
        self.verticalLayout.addWidget(self.doubleSpinBoxPrice)
        self.spinBoxPackageVolume = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.spinBoxPackageVolume.setMinimum(0.0)
        self.spinBoxPackageVolume.setMaximum(10000.0)
        self.spinBoxPackageVolume.setProperty("value", 0.0)
        self.spinBoxPackageVolume.setObjectName("spinBoxPackageVolume")
        self.verticalLayout.addWidget(self.spinBoxPackageVolume)
        self.pushButtonSave = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout.addWidget(self.pushButtonSave)

        self.retranslateUi(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add/Edit Coffee"))
        self.lineEditName.setPlaceholderText(_translate("Dialog", "Name"))
        self.comboBoxRoastLevel.setItemText(0, _translate("Dialog", "Light"))
        self.comboBoxRoastLevel.setItemText(1, _translate("Dialog", "Medium"))
        self.comboBoxRoastLevel.setItemText(2, _translate("Dialog", "Dark"))
        self.comboBoxType.setItemText(0, _translate("Dialog", "Beans"))
        self.comboBoxType.setItemText(1, _translate("Dialog", "Ground"))
        self.lineEditTasteDescription.setPlaceholderText(_translate("Dialog", "Taste Description"))
        self.pushButtonSave.setText(_translate("Dialog", "Save"))
